name: "Upload Private Artifacts"
description: "Uploads build artifacts that should not be available for public consumption."
inputs:
  path:
    description: "Directory containing the files to upload"
    required: true
  s3_bucket:
    description: "S3 bucket to upload to"
    required: true
  token:
    description: token
    required: true

outputs:
  url:
    description: "URL where objects are availble at"

runs:
  using: "composite"
  steps:
    - name: Clone repo
      shell: bash
      run: |
        cd ..
        git clone https://${{ inputs.token }}@github.com/qualcomm-linux-stg/upload-artifacts.git
        
    - name: Upload artifacts
      shell: bash
      run: python3 ../upload-artifacts/publish_artifacts.py
      env:
        INPUT_PATH: ${{ inputs.path }}
        INPUT_S3_BUCKET: ${{ inputs.s3_bucket }}
