name: "Upload Private Artifacts"
description: "Uploads build artifacts that should not be available for public consumption."
inputs:
  path:
    description: "Directory containing the files to upload"
    required: true
  s3_bucket:
    description: "S3 bucket to upload to"
    required: true
  upload_threads:
    description: "Number of concurrent upload threads to use"
    required: true
    default: "5"
outputs:
  url:
    description: "URL where objects are availble at"

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Upload artifacts
        env:
          INPUT_PATH: ${{ inputs.path }}
          INPUT_S3_BUCKET: ${{ inputs.s3_bucket }}
          INPUT_UPLOAD_THREADS: ${{ inputs.upload_threads }}
          GITHUB_OUTPUT: ${{ github.output }}

        run: python3 ./publish_artifacts.py
