name: Unit Test

on:
  pull_request:
    branches:
      - aws
  push:
    branches:
      - aws

jobs:
  unit-test:
    runs-on: [self-hosted, qcom-u2404, arm64]
    steps:
      - name: Create artifacts
        run: |
          set -eux

          mkdir build
          echo 8675309 > build/test-artifact.txt

      - name: Upload artifacts
        id: upload
        uses: qualcomm-linux/upload-private-artifact-action@aws
        with:
          path: ./build
          s3_bucket: qcom-prd-gh-artifacts
          destination: unit-test/${{ github.run_id }}-${{ github.run_attempt }}/

  unit-test-container:
    runs-on: [self-hosted, qcom-u2404, arm64]
    container:
      image: public.ecr.aws/debian/debian:trixie
      options: --volume /home/runner/.aws:/root/.aws
    steps:
      - name: Create artifacts
        run: |
          set -eux

          mkdir build
          echo 8675309 > build/test-artifact.txt

      - name: Upload artifacts
        uses: qualcomm-linux/upload-private-artifact-action@aws
        with:
          s3_bucket: qcom-prd-gh-artifacts
          destination: unit-test/${{ github.run_id }}-${{ github.run_attempt }}/
          path: ./build
