name: Unit Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install black mypy types-requests types-boto3

      - name: Run mypy
        run: |
          mypy ./publish_artifacts.py

      - name: Run black
        run: |
          black --check --diff ./publish_artifacts.py


  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Create artifacts
        run: |
          set -eux

          mkdir build
          echo 8675309 > build/test-artifact.txt

      - name: Upload artifacts
        id: upload
        uses: qualcomm-linux/upload-private-artifact-action@main
        with:
          path: ./build

      - name: Print URL
        env:
          URL: ${{ steps.upload.outputs.url }}
        run: |
          set -eu
          echo "URL is ${URL}"

  unit-test-container:
    runs-on: ubuntu-latest
    container:
      image: debian:trixie
    steps:
      - name: Create artifacts
        run: |
          set -eux

          mkdir build
          echo 8675309 > build/test-artifact.txt

      - name: Upload artifacts
        id: upload
        uses: qualcomm-linux/upload-private-artifact-action@main
        with:
          path: ./build

      - name: Print URL
        env:
          URL: ${{ steps.upload.outputs.url }}
        run: |
          set -eu
          echo "URL is ${URL}"
